
image: gradle:jre11-slim

stages:       
  - test
  - test-sonarcloud
  - build
  - deploy
test:
  script:
    - gradle clean test 
test-sonarcloud:
  stage: test-sonarcloud
  variables:
   SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
   GIT_DEPTH: "0"  
  image:
    name: gradle:jre11-slim
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
      - gradle sonarqube -Dsonar.qualitygate.wait=true
  only:
    - main
build:
  stage: build
  script:
    - gradle assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - main
deploy:
  stage: deploy
  script:
    - ./deploy

after_script:
  - echo "End CI"





